### ISSUE TITLE
Világmodell / háromszög felderítés

### ISSUE THREAD

**Issue by kuklinistvan** [SzFMV2021-Tavasz/AutomatedCar-A#106]
Legyen a World-ön egy függvény, aminek adunk egy háromszöget, ez pedig visszaadja a benne lévő elemeket. (kamera felderítéshez fog kelleni)

**Comment by kuklinistvan** [comment]
Konzultáción elhangzott (márc .11.): három pontot fogadunk és kész. Nem szögeket, távolságokat.

**Comment by kuklinistvan** [comment]
> Konzultáción elhangzott (márc .11.): három pontot fogadunk és kész. Nem szögeket, távolságokat.
@pintergreg, approve-ot kérünk

**Comment by pintergreg** [comment]
> (kamera felderítéshez fog kelleni)

Bármely szenzor, de igen, pontosan erről van szó. 

> @pintergreg, approve-ot kérünk

Approved.

**Comment by kuklinistvan** [comment]
Elkezdtem a teszteket. Egy teszteset bemenetei:

* a háromszög 3 pontja,
* összesen hány objektumot kéne érzékelni,
* érzékelt objektumok típus szerint tömbben,
* érzékelt objektumok mennyiségei az előző tömb szerint.

Pl. ez a teszteset:
```
[TestCase(10, 10, 20, 20, 50, 80, 1, new[] {WorldObject.Type.MAN}, new[] {1})]
```
A háromszög, amelyet az alábbi koordináták határoznak meg:  `(10; 10); (20; 20); (50; 80)`, egy objektumot kell érzékelnie összesen, ez lebontva egy darab `MAN` objektum.

* [ ] **Feladat a)** Ki kell találni, honnan szerzünk teszteseteket (vagy vizualizáljuk valahogy mi a világot és az ütközési poligonokat, vagy ami talán egyszerűbb - kitaláljuk / megkérdezzük a többi csapattól, hogy hogyan lehet világot betölteni, hogy láthassuk, nagyjából mi hol van)

* [ ] **Feladat b)** Implementálni kell a háromszög-átfedéses felderítést a [`World.cs`-ben](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/pull/111/commits/898166a929d472d68f78ab40624531804f9c4467#diff-05421f63a7d205c7bb6e1cecfc735bc9cff678403de589b9cd46494ad473e2e1R120).

**Comment by pintergreg** [comment]
Én azt mondanám, hogy kezeld úgy mintha mock-olnál. Létrehozol egy üres world-öt, beleteszel egy fát, vagy a dummy circle obkektumot, kicsit úgy mint a skeleton példájában van és megnézed, hogy beleesik-e egy háromszögbe.

Én nem építenék föl ennél komplexebb világot a „háromszöges szűrés” unit tesztjéhez. Azt már integrációs tesztnek gondolom, hogy ha betöltesz egy teljes világot és azon tesztelsz.

**Comment by vajnaivik** [comment]
@Sumakolo Került fel teszt adat, itt vannak ábrázolva képen illetve Geogebrában. Van néhány háromszög is, ezek lehetnek például teszt esetek.
![1](https://user-images.githubusercontent.com/61936589/110845770-4b57dd00-82ab-11eb-908a-4f2f8c1ceac2.png)
![2](https://user-images.githubusercontent.com/61936589/110845771-4bf07380-82ab-11eb-9a82-d1fd65cb78ee.png)
![3](https://user-images.githubusercontent.com/61936589/110845773-4bf07380-82ab-11eb-8990-153b6556db93.png)
[geogebra-export.zip](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/files/6125605/geogebra-export.zip)

**Comment by kuklinistvan** [comment]
TODO: kiterjedt poligonokra is. Jó lesz :)

**Comment by vajnaivik** [comment]
@SzFMV2021-Tavasz/team-a2 No így kicsit kevesebb lett, de legalább használható :D

Az adatokhoz ajánlott teszt esetek és kimeneteik:
(0, 0), (0, 80), (200, 0):  1 man
(40, 80), (40, 400), (620, 400): 1 tree, 1 boundary, 1 garage
(220, 0), (340, 0), (340, 160): 1 roadsign_speed_60
(700, 0), (50, 700), (700, 700): 1 car_1_blue, 1 bicycle, 1 garage

![image](https://user-images.githubusercontent.com/61936589/110986354-da2d2e00-836d-11eb-96a6-f20e6bd36b7c.png)
[geogebra-export.zip](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/files/6132364/geogebra-export.zip)

**Comment by vajnaivik** [comment]
@SzFMV2021-Tavasz/team-a2 Az utakkal kapcsolatban van egy pár észrevételem így kirajzoltatás után, amire érdemes lehet figyelni.

Az utak poligonjainál a poligonok nem a sávokat, hanem azok határait jelölik.
"standalone" és "lane" tipusú polyn kívül van "curve" is.

Ezek a megoldások érthetőek is, az intersect-el használhatjuk őket.
A curve úgy sejtem ezért van megkülönböztetve:
![image](https://user-images.githubusercontent.com/61936589/111692753-12ca7d00-8830-11eb-9725-ca8b30c42aea.png)
Ez a dolog ott vérzik el, hogy a kanyaroknál, (mint pl a "road_2lane_90left") nem curve, hanem lane van használva.

Érdemes lehet a lane és curve típust is vonalként kezelni, remélem arra is lehet intersectet hívni valahogy.

**Comment by vajnaivik** [comment]
Került fel teszt adat az utakhoz is.
Az adatokhoz teszt esetek lehetnek ezek:
(300, 1500), (1000, 1500), (1000, 1700): üres
(300, 1400), (1300, 1400), (1300, 1100): 3 poly
(950, 700), (1500, 800), (1500, 600): 1 poly
(1650, 150), (2100, 300), (2100, 0): 2 curve
(2450, 700), (2500, 450), (2400, 450): üres
(2000, 900), (2300, 1300), (1700, 1300): 3 poly
(400, -400), (1000, -200), (1000, -600): üres

A teszt esetek és utak ábrázolva:
![image](https://user-images.githubusercontent.com/61936589/111697949-85d6f200-8836-11eb-9670-016854e71d14.png)
[geogebra-export-2.zip](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/files/6167219/geogebra-export-2.zip)
