### ISSUE TITLE
Automatikus build során dotnet restore fail

### ISSUE THREAD

**Issue by goet** [SzFMV2021-Tavasz/AutomatedCar-A#118]
Lásd: https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/runs/2107104572?check_suite

Mivel project file-okhoz egyáltalán nem nyúltam nem hiszem hogy én törtem el valamit, de ötletem sincs hogy ez eddig miért nem dobott hibát.

**Comment by kuklinistvan** [comment]
Hahó! :) Az a tapasztalatom, hogy másodszorra néha sikerül. Indítsd el a check-eket újra, hátha ;)

**Comment by pintergreg** [comment]
@goet nekem is az a tapasztalatom amit @kuklinistvan mondott, újrafuttatva most zöld. Sajnos nem tudom mi okozza.

**Comment by Easimer** [comment]
Még annó amikor írtam #55-ot akkor utána néztem és úgy tűnik, hogy valami a nuget cache-el rossz és néha beragadnak nuget csomagok a cacheben:
https://github.com/actions/setup-dotnet/issues/155
A workaround erre az, hogy clearelni kell `dotnet restore` előtt a pkg cachet dotnet.yml-ben:
```
- name: Clean
      run: dotnet clean && dotnet nuget locals all --clear
```
vagy nuget.config-ban:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by pintergreg** [comment]
@Easimer Hozzáadtam a GH Actions confighoz a clean-t.
