### ISSUE TITLE
Polygon osztály pont redundanciát szüntessük meg

### ISSUE THREAD

**Issue by kuklinistvan** [SzFMV2021-Tavasz/AutomatedCar-A#139]
![kép](https://user-images.githubusercontent.com/19473224/111756686-c9fbde00-889a-11eb-96fa-940dced823be.png)

A Polygon-on belül döntsük el hogy melyik szimpatikusabb (én már csak azért maradnék a Tuple-nél, mert lehet, hogy mások már építettek rá), és csak azt az egyet tartsuk meg.

![kép](https://user-images.githubusercontent.com/19473224/111756719-d2541900-889a-11eb-93db-2a5c41e0afc1.png)

Köszönöm szépen előre is!

**Comment by pintergreg** [comment]
A PPoints szerintem sem a legjobb. Talán a #109 -ben vetette fel valaki, hogy lehetne (?WPF.)Point, mert nekik arra kell később alakítani. Valami olyasmi volt az érvelése, hogy szebb az a hívóoldali api, hogy ReferencePoint.X mint az ReferencePoint.item1...

A WPF linkelés kapcsán ugyanaz a szitu mint ami a Shape/Geometry körül volt: attól, hogy egy WPF típust használtok nem függtök a megjelenítéstől.

_De ez lehet, hogy itt egy másik esetről van szó._

**Comment by kuklinistvan** [comment]
> Valami olyasmi volt az érvelése, hogy szebb az a hívóoldali api, hogy ReferencePoint.X mint az ReferencePoint.item1...

Ez egy másik probléma, de ugyanez a Tuple volt a problémás ott is. A PPoint egy algoritmus következményeként került bele, amire mondtam alternatív megoldást. 

> A WPF linkelés kapcsán ugyanaz a szitu mint ami a Shape/Geometry körül volt: attól, hogy egy WPF típust használtok nem függtök a megjelenítéstől.

Ezzel én egyetértek.

**Comment by goet** [comment]
Anekdotikus de,
- Munkám során főként a System.Drawing.Point osztályt láttam erre használva, még olyan esetekben is amikor a C# kód csak szerver backendért felelt, tehát amúgy semmilyen megjelenítéssel nem foglalkozott.
- Hobbim során játékmotorokban Vector2-őt használnak erre, szerintem ez is egy teljesen konvencionális út lenne az esetünkben, a vizualizációs rész is inkább hasonlít egy motorra mint egy tradícionális forms-os alkalmazásra.
- Ha esetleg ez a kettő túl "bloatos" (mi erre a magyar szó?) megoldás lenne, szerintem még mindig játszhat hogy fokozatosan áttérünk egy saját pont structra, ahol aztán már teljesen irányíthatjuk hogy mi hogyan működik, de eddigi tapasztalatok alapján teljesen elegendő ha csak van két koordinátája, illetve itt van lehetőségünk override-al implicit MiMenőPointunk -> System.Drawing.Point konverziót definiálni
- Ha rosszabbá akarjuk tenni a helyzetet akkor definiálhatjuk ezeket unsafe kódként, és akkor már elérhetőek számunkra a főként gpu programozásnál használt float2-3-4 típusok :D

**Comment by kuklinistvan** [comment]
A problémát időközben orvosoltuk a #111-ben. Az a megoldás született, hogy a Tuple-t benne hagytuik, de készítettünk mellé egy Point-os on-the-fly konvertáló getter-t. Ha ez nem jó, nyissátok  újra az issue-t vagy tegyetek észrevételt a PR-ban. Köszönöm előre is!
