### ISSUE TITLE
Vészfékező implementálása statikus objektumokkal

### ISSUE THREAD

**Issue by goet** [SzFMV2021-Tavasz/AutomatedCar-A#178]
Az autónak figyelnie kell a saját sebességét, és az alapján megmondani hogy a veszélyes objektum minimum féktávolságon belül van-e. Amennyiben igen, a buszra ki kell tennie egy packetet, ami alapján a hajtáslánc rátapos a fékre.

**Comment by szabogaliakos** [comment]
[Fektavolsag.xlsx](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/files/6353211/Fektavolsag.xlsx)
