### ISSUE TITLE
Világmodell kialakítása

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2021-Tavasz/AutomatedCar-A#2]
A *világmodell* modul felelőssége a játék virtuális terének felépítése, az abban található elemek Objektum Orientált elveknek megfelelő hierarchiába szervezése, a virtuális tér elemeivel való interakciót biztosító (publikus) metódusok implementálása.

A modul bemenete a világ statikus elemeit tartalmazó állomány, amely XML és JSON formátumban is rendelkezésre áll. Ez a leíró fájl azonban csupán az objektumok síkbeli helyzetét, elforgatását és típusát tartalmazza. A modul felelőssége a többi modul igényeivel összhangban az objektumok további tulajdonságokkal történő felruházása. Például a rajzolást megkönnyíző *Z index* vagy az objektum térbeli kiterjedését szolgáló poligon definiálása.

A modullal kapcsolatos legfontosabb kihívás, hogy más csapatoktól érkező igényeket is teljesíteni kell, és „mindenki ezekre vár”. Így különösen fontos kezelni a sprinten belüli határidőket és prioritásokat. Például a deszerializált világobjektumok az első pillanattól kezdve szükségesek a megjelenítésért felelős csapat számára.
Valamint, hogy minden tervezési döntés érinti a többi csapatot is, még ha ők ennek nincsenek is mindig tudatában.

- Mielőbb el kell dönteni, hogy milyen koordináta-rendszerben dolgozik majd a modell.
Teljesen járható út, hogy a modell, az input állományban található koordináta-rendszer egy az egyeben alkalmazásra kerül, ebből adódóan minden számolás abban történik, csak a megjelenítés transzformálja át. (A teljes világ nem fog kiférni a képernyőre.)
- El kell dönteni, hogy mi legyen az objektumok referenciapontja. A megjelenítés során forgatni kell az objektumokat, a [forgatási pont](virtual_world.md#az-%C3%BAt-elemek-viszony%C3%ADt%C3%A1si-pontjai) nem egyezik meg a referenciaponntal, de a megjelenítésnek szükséges.
- A világ objektumokhoz poligonokat kell társítani, ezek szolgálnak majd az ütközés valamint a látótérbe kerülés eldöntésére.
- Fontos továbbá, hogy ezek a poliginok nem a képfájl szélei. A fa esetében csupán a törzsének lehet nekimenni, nem a lombkoronának, ezért a modellt ekképpen kell megalkotni! A törzsnek használható egy szabályos hasáb az egyszerűség kedvéért.
    - ![](https://raw.githubusercontent.com/SzFMV2021-Tavasz/handout/master/src/images/tree_collidable.png)
- Az autó is egyszerűsíthető, nem kell a grafikai elemet teljes mértékben követni.
    - ![](https://raw.githubusercontent.com/SzFMV2021-Tavasz/handout/master/src/images/car_simplified_polygon_model.png)
- A kanyarodó útelemeknél is lehet egyszerűsítést használni.
    - ![](https://raw.githubusercontent.com/SzFMV2021-Tavasz/handout/master/src/images/90left_polygon.png)
- A szűréshez használt háromszög esetében a poligonokat kell figyelembe venni, pl. fa törzse, tábla rúdja, de nem csak az „ütközhető” objektumokat kell tudni visszaadni, hanem az útelemeket is. A 2. sprintben a szenzorok majd válogatnak, hogy mire van szükségük ezekből.
    - ![](https://raw.githubusercontent.com/SzFMV2021-Tavasz/handout/master/src/images/model_interface.png)
- A poligonok megrajzolásához használható a [VGG Image Annotator](https://www.robots.ox.ac.uk/~vgg/software/via/), amely [böngészőből is működik](https://www.robots.ox.ac.uk/~vgg/software/via/via.html) és a megrajzolt polygont JSON-ben le lehet menteni.
    - Korábbi félév során @ArchiCat és @konyarilaszlo ezt már megtette, elérhető a [worldobject_polygons.json](resources/worldobject_polygons.json) állományban.
- A poligonok definiálásához célszerű a [java.awt.geom](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/geom/package-summary.html) névteret használni. Ezek `intersects` könnyedén eldönthető, hogy egy objektum a szenzor látóterében van-e (amennyiben a szenzor is egy ilyen poligon).
- A statikus objektumokon kívül a világ modell részét kell képzzék dinamikus, mozgó objektumok is.

A tervezés során nem elegendő csupán az első sprint (meglehetősen szűk) követelményit figyelembe venni, hanem célszerű ezen túl a későbbi sprintek során valamennyi *user story*-ban felbukkanó követelmény kezelése. Természetesen nem elvárás a „jövőbe látás”, de törekedni kell minden logikusan előrelátható követelmény kezelésére.

### Definition of Done

- [ ] Útelemeket, fákat, táblákat egyéb statikus objektumokat leíró állományok feldolgozása (deszerializálása)
    - [ ] kicsi pálya (test_world) és elemeinek megfelelő kezelése
    - [ ] nagy pálya (test_world_1kmx1km) és elemeinek megfelelő kezelése
- [ ] Hierarchikus objektummodell implementálása világ leírására, API biztosítása ennek elérésére,  lekérdezésére
- [ ] Objektumok kiterjedését biztosító poligonok definiálása
- [ ] Minden feldolgozott objektum rendelkezzen pozíció, referencia, orientáció, típusadatokkal
- [ ] A modell legyen felkészítve az input fájlból kiolvasott „statikus” objektumokon túl mozgó („dinamikus”) objektumok kezelésére is
    - vezérelt autó, NPC (non-player-character) autó, gyalogos
- [ ] A modell tegyen különbséget azon objektumok között amelyeknek egy jármű nekimehet és amelyeknek nem (fa vs. útelem)
- [ ] A modell kezeljen „z-index”-et, hogy a kirajzolás során biztosítható legyen, hogy mely elemet kell előtt kirajzolni a „kitakarások” végett

**Comment by kuklinistvan** [comment]
@vajnaivik @Sumakolo 

Sziasztok! Kérek szépen tőletek egy köpködést :) 
A draw.io forrás is benne van, ha belerajzolnátok.

[tervek.zip](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/files/5980758/tervek.zip)

![tervek](https://user-images.githubusercontent.com/19473224/107931064-18584d00-6f7c-11eb-85cb-1d37abe59ee7.png)

**Comment by kuklinistvan** [comment]
@pintergreg, ezeket szeretnénk megkérdezni:

> Hierarchikus objektummodell implementálása világ leírására, API biztosítása ennek elérésére, lekérdezésére.

Miért ennyire hangsúlyos, hogy hierarchikus objektummodell? Kaphatunk erre ellenpéldát (hogyan lehetne ezt "rosszul" megoldani)?

> A modell legyen felkészítve az input fájlból kiolvasott „statikus” objektumokon túl mozgó („dinamikus”) objektumok kezelésére is.

Jól értettük -e, hogy a világunk nem pusztán egy bárki által bármilyen módon szerkeszthető homokozó, hanem vannak szabályai is - és ennélfogva,  a többi modulnak nem lehet csak úgy "felülről belenyúlnia" a tartalmába, hanem ehelyett az API által megkövetelt módon kell azzal interaktálnia? (pl. a tick() függvény hatására, amit objektumonként meghívhatnánk minden körben)

> A szűréshez használt háromszög esetében a poligonokat kell figyelembe venni

Jól értjük, hogy a háromszöges felderítés tulajdonképpen az autó és egyéb objektumok szenzorai által belátott területre irányul?

**Comment by pintergreg** [comment]
@kuklinistvan ,

> Miért ennyire hangsúlyos, hogy hierarchikus objektummodell? Kaphatunk erre ellenpéldát (hogyan lehetne ezt "rosszul" megoldani)?

Az az elképzelésünk, hogy a világ egy gyűjteményben tartalmazza az összes világon belüli objektumot: autót, gyalogost, fát, táblát, útelemeket, stb. Ezt értelemszerűen akkor tudod megtenni ha ezeknek van valami közös őse (szoktam a jegyzetben is WorldObject-ként hivatkozni). Bár a világnak nem kell tudnia, hogy mi micsoda, de az egyes modulok viszont majd nagyon specifikusan adott fajta objektumokra lesznek kíváncsiak. Pl. a radar „látja” a gyalogost, de nem látja az útelemet. A táblafelismerőnek kifejezetten csak táblák kellenek.

Anno az elképzelés egy léggé „mély” hierarchia legyen, pl.

- világelem
  - út
    - egyenes
    - kanyar
      - 90 fokos
      - 45 fokos
  - fa
  - tábla
- stb

A hierarchikus szó emiatt van, de volt már olyan implementáció, amikor valamilyen attribútum érték és nem típusvizsgálat alapján ment a szétválogatás. Nem kötelező tehát ilyen osztályokat csinálni (bizonyos szempontból erőltetetten OO), de biztosítani kell, hogy könnyen szűrhető az igényeknek megfelelően.

Lehet, hogy egy _„jól szűrhető” objektummodell_ jobb kifejezés lenne.

> Jól értjük, hogy a háromszöges felderítés tulajdonképpen az autó és egyéb objektumok szenzorai által belátott területre irányul?

Igen. Szenzorai a vezérelt autónak lesznek, ezek látómezeje egy-egy háromszöggel van reprezentálva. Vissza kell tudni adni a világból azokat az objektumokat, amelyek beleesnek egy ilyen háromszögbe.

(A fent említett szűrést a lekérdező modul fogja elvégezni.)

> Jól értettük -e, hogy a világunk nem pusztán egy bárki által bármilyen módon szerkeszthető homokozó, hanem vannak szabályai is - és ennélfogva, a többi modulnak nem lehet csak úgy "felülről belenyúlnia" a tartalmába, hanem ehelyett az API által megkövetelt módon kell azzal interaktálnia?

Igen, teljes mértékben. A világleíró fájlból feltöltitek a világot ún. statikus objektumokkal. Ezek jellemzően nem mozognak (fa, út), de egyes tulajdonságaik ekkor változhatnak: a megjelenítésnek meg kell tudja jelölnie objektumokat, ennek vizualizálása pl. hogy sárgára van festve. Egy szenzor beállíthat egy „highlighted” értéket a fán és annak függvényében a megjelenítés sárgával tölti ki az objektumot. Ebben az esetben a highlighted mező a modell lefixált része, csak úgy nem kerül bele „felülről”. De egy másik csapat kérheti, hogy kerüljön bele egy _foo_ mező, mert neki kell.

A „felülről” részt remélem nem értem félre. Másik példa: a vezérelt autó mozgatását pl. a 3-as csapat intézi. A számításaik végén átírják  a világ részét képező AutomatedCar objektum X, Y és Rotation értékeit. Amit a megjelenítés kiolvas és felhasznál.

Bevallom, a tickes példát nem értem.

---

Első blikkre az ábrával kapcsolatban: az XML/JSON használata a ti döntésetek, _tervezési időben_. A kódban már elég kizárólag az egyiket használni, amelyik kényelmesebb.

**Comment by kuklinistvan** [comment]
@pintergreg, köszönjük a választ, azt hiszem, világos!

@vajnaivik, @Sumakolo az `ObjectControlAPI`-t ki kéne egészíteni annyival, hogy a `QuerySensors()` ne adjon vissza minden útbaeső dolgot, hanem csak azokat, amiket az objektum látni tud.

A látható objektumok kijelölésére biztosítani kell valamilyen módot - én azt tartom most hirtelen a legrugalmasabb megoldásnak, ha objektumonként beállítanánk flag-eket, hogy ki láthatja. Természetesen, az objektum készítő oldalon senki nem akadályozza meg azt, hogy az `ObjectControlAPI`-t úgy implementálják, hogy ezeket bele hard code-olják az objektumhierarchiába, ha úgy jobbnak látják. A működés oldaláról csak annyit tartok lényegesnek, hogyha az `ObjectControlAPI` használója meghívja a `QuerySensors()`-t, akkor valahogyan az API implementációja megoldja, hogy csak olyan objektumok listázódjanak, amiket az adott objektum "láthat". A `GenericWorldObject_API` egy példa, akár használható implementáció is lehetne, ami a tag-ekre épít.

![világmodell](https://user-images.githubusercontent.com/19473224/107950854-a857c000-6f97-11eb-8ec1-529600d07966.png)
[tervek.zip](https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/files/5981706/tervek.zip)

@pintergreg 
> Egy szenzor beállíthat egy „highlighted” értéket a fán és annak függvényében a megjelenítés sárgával tölti ki az objektumot.

A világnak (szimulációnak) biztosan tudnia kell róla, hogy egy adott GUI-n valami hogyan jelenik meg? Ez nem a GUI oldal dolga, hogy rögzítse azoknak az objektumoknak az ID-it, amiket highlighted-nek gondol? (SRP)

> Bevallom, a tickes példát nem értem.

A szimuláció minden körben azonos idő deltákkal meghívja sorra az objektumok `tick()` függvényeit, amiknek ilyenkor lesz lehetőségük interaktálni a a világgal az `ObjectControlAPI`-n keresztül. Az `ObjectControlAPI` implementációját az `InMemoryWorld` fogja odaadni az `OnTick()` függvénynek.

**Comment by pintergreg** [comment]
> A világnak (szimulációnak) biztosan tudnia kell róla, hogy egy adott GUI-n valami hogyan jelenik meg? Ez nem a GUI oldal dolga, hogy rögzítse azoknak az objektumoknak az ID-it, amiket highlighted-nek gondol? (SRP)

Ezt nem a megjelenítés gondolja annak, hanem a szenzor (aminek van egy olyan követelménye, hogy jelölje meg a legközelebbi objektumot), ami a vezérelt autó része(, ami a világ része). A megjelenítés csak megjelenít. Olvassa (és kizárólag olvassa) a világ objektumait és rajzol, adott helyre, adott elforgatással(, egyes tulajdonságainak függvényében esetleg más színnel). [Valahogy így](https://szfmv2021-tavasz.github.io/handout/images/full_software.png).
A megjelenítéstől azt várjuk, hogy meg tudjon különböztetni, kiemelt és nem kiemelt objektumokat vizuálisan. A döntést nem ő hozza és nincs is rá hatása. Szerintem így nem sérül a SRP, de elfogadom ha tévedek.

> A szimuláció minden körben azonos idő deltákkal meghívja sorra az objektumok `tick()` függvényeit, amiknek ilyenkor lesz lehetőségük interaktálni a világgal az `ObjectControlAPI`-n keresztül. Az `ObjectControlAPI` implementációját az `InMemoryWorld` fogja odaadni az `OnTick()` függvénynek.

Oké, de biztos, hogy minden objektumnak szüksége van erre? Pontosabban itt ki az alany? Az egyes modulok?

Tegyük fel, hogy én egy szenzor vagyok, épp elkértem a query-vel a látóteremben levő objektumok( referenciák)at, és kiválasztottam egy fát. Ebben az esetben szeretném ha lenne egy lehetőségem a tree.setHighlighted() metódust meghívni (mindegy minek nevezzük).
A világ, a fa vagy a szenzor tick-je számít itt? 

Nehezíti a helyzetemet, hogy az autó belső architektúrája is használ egy timer-t, ami az autó belső komponenseit hívja sorban, a múlt féléves Avalonia-s megoldásnak meg volt egy második ablak/keretrendszer szintű timer-e is, és szerintem keverem a dolgokat, de ez nem jelenti azt, hogy „rossz” lenne az elképzelésetek.

**Comment by kuklinistvan** [comment]
> A megjelenítéstől azt várjuk, hogy meg tudjon különböztetni, kiemelt és nem kiemelt objektumokat vizuálisan. 

Lehet, hogy kezdem érteni. Egy szenzornak van mindig egy (a legközelebbi) eleme, amit kiemeltnek tekint? A GUI pedig követ egyetlen, az autóból kifelé néző szenzort, és annak a kiemelt objektumát jeleníti meg? Ha igen, akkor világos.

> Oké, de biztos, hogy minden objektumnak szüksége van erre? Pontosabban itt ki az alany? Az egyes modulok?

Azokon az objektumokon hívnám meg, aminek van `CAN_TICK` engedélye.

> Ebben az esetben szeretném ha lenne egy lehetőségem a tree.setHighlighted() metódust meghívni (mindegy minek nevezzük).

Én "laikus" vagyok, de megfordítanám: (kicsit messziről indulok) az API-nk egy motor (legalább is, amit rajzoltam), ahhoz modulárisan bármilyen objektum beadható, ami ki tudja tölteni az `ObjectInWorld_Properties` objektumot. Ha ez dinamikus, tehát van logikája, azt megjelöljük a `CAN_TICK`-kel, így `Tick()`-re ő is sorra kerülne, és frissíteni tudná az állapotát az eltelt idő függvényében.

A szenzor az egy autóba DI-vel építhető objektum, ami OnTick()-re a hozzárendelt autó helyzete alapján megnézi, hogy mit lát a query-vel, majd jelenti valahogyan a GUI felé a kiemelt objektum handle-jét. Tulajdonképpen felfelé propagál egy eseményt. A GUI ezt megkapja, kikeresi ez alapján az objektumot, lekéri a pozícióját és kiemeli. Ez az elképzelésem.

**Comment by kuklinistvan** [comment]
ui: a `CanBeSeenBy` enummal elkövettem azt a hibát, hogy bele hardcode-oltam a támogatott objektumok típusát az API-ba. Szebb megoldás lenne hogyha a CanBeSeenBy csak típus osztályokat definiálnának (`CAMERA_LIKE_OBJ`, `CAR_LIKE_OBJ` (vehicle?))

**Comment by vajnaivik** [comment]
@pintergreg Készült egy alternatív terv is az előző mellett, ami kicsivel talán egyszerűbb felépítésű.
![diagram](https://user-images.githubusercontent.com/61936589/107990628-1ec6e300-6fd5-11eb-9552-556e528619f1.png)

Még kevésbé kidolgozott ugyan, de kíváncsiak lennénk a véleményedre. Itt egy csapaton belüli összehasonlítás is a kettőről:
Az utóbbi objektumok, és annak hierarchiájának fix készlete, egyszerűbb, de nem annyira bővíthető, és felveti a kérdéseket, hogy hányszor fogunk egymás kódjába belenyúlni (egészen pontosan a Tick() függvénybe, lévén ott történik a dolgok meghajtása). A Tick() nem definiál időt, ezért a hívás gyakoriságától fog függeni az objektum sebessége. Az utóbbi valószínűleg igényelni fog reflexiót is (a type kiderítésére).

Az előbbi jobban izolált, sokkal több benne a DI, kevesebb a coupling. Ez egy nyers motor, egy API, ami önmagában semmilyen objektumot nem tartalmaz. Beégetve csak néhány címke van, és a működési rutin. Lehetővé teszi a használójának objektumok definiálását és beaddolását, majd ütemezetten vezérli őket. Lehetővé teszi a logikák definiálását a használója által. Summa: jobban bővíthető, talán fenntarthatóbban fejleszthető, viszont meg kell barátkozni vele, hogy az objektumok tulajdonságai nem az API-ban vannak benne, hanem beaddolható bővítményekként.

**Comment by pintergreg** [comment]
> Egy szenzornak van mindig egy (a legközelebbi) eleme, amit kiemeltnek tekint? A GUI pedig követ egyetlen, az autóból kifelé néző szenzort, és annak a kiemelt objektumát jeleníti meg? Ha igen, akkor világos.

Nem, a gui felülnézetes, és a vezérelt autót (játékos autó) követi. Annak van szenzora ami lát dolgokat a világból és alapvetően saját célra kiválaszt a látottakból.

![Képernyőkép_2021-02-16_09-48-44](https://user-images.githubusercontent.com/3854784/108039578-8d8b5700-703c-11eb-8ade-28541b530dfb.png)

Nem látszik, mert nem tudtam reprodukálni a a kiemelést, de itt a fa benne van a kék látómezőben. Tegyük fel, hogy kiemeli.
Ezt a szenzor azért teszi, mert a vezetéstámogató funkció dolgozik majd vele. De van egy „csavar” a történetben: az egészet debuggolni és demózni kell, ezért azt kérjük a megjelenítéstől, hogy ha valami ki van emelve, azt vizuálisan különböztesse meg a többitől. Azért, hogy a fejlesztő dolga egyszerűbb legyen és azért, hogy a demón könnyebben bemutatható legyen.
Ez a kiemelés megjelenítés egy „mesterséges” dolog. Az viszont tény, hogy a megjelenítéssel nem nagyon kommunikálhat egy szenzor. Az mindenféle elvet sértene.

_a többi dologra nem volt most időm most reagálni, még később még foglalkozom vele_

**Comment by kuklinistvan** [comment]
@pintergreg Szerintem elbeszélünk egymás mellett. Van lehetőség szóban konzultálni valamikor?

**Comment by pintergreg** [comment]
@kuklinistvan Valóban nem teljesen értem a logikát és kicsit elbonyolítottnak találom.

Általában igen, holnap nem sok időm lesz. Most beléptem Teamsre, kb. 6-ig online is is leszek, ha épp ráérsz. De  csütörtökön az óra 2. felében, konkrétan foglalkozunk ezzel. Nem vagytok elkésve semmivel.

@vajnaivik Rajzolásban, vagy logikában alternatív? Ugye nem két külön megoldás készült?

**Comment by vajnaivik** [comment]
@pintergreg Logikában alternatív, a mellékelt kép alatt van egy összehasonlítás is a kettő felépítésről. Ha ráérsz megnézni, szívesen fogadnánk egy véleményt róla.

**Comment by kuklinistvan** [comment]
@pintergreg Rövidebben a különbség: @vajnaivik kolléga megoldásába a játékelemek hard code-olva vannak. Bővíteni csak akkor lehet, ha beleírunk. Az enyém moduláris. Az enyémhez bárki írhat elemeket, akár logikával, anélkül, hogy velem egyeztetne, és a munkámat módosítaná.

**Comment by kuklinistvan** [comment]
@pintergreg @vajnaivik @Sumakolo 
Megpróbáltam "táblánál" elmondani:
https://www.youtube.com/watch?v=FKL1fxfNOgM&feature=youtu.be

**Comment by pintergreg** [comment]
@SzFMV2021-Tavasz/team-a2 
Megértettem a különbséget, már a videó előtti két posztból is leesett, de azt is megnéztem.

Olyan értelemben értettem azt, hogy „túl bonyolult”, hogy a hardcode-olt rész programozásilag és megértésileg talán egyszerűbb, de pont az a hátránya ami te is elmondtál a videóban és fenn is szokott állni. Az elképzelés alapján egyébként nem kell „elsőre eltalálni” hanem le kell egyeztetni, hogy mi legyen benne. Mármint a többi csapattal. Persze legalább egy csapat nem fogja tudni elsőre, hogy mit akar magával kezdeni ezért lesznek még iterációk... Ennek akarod elejét venni.

Mivel a videó részletesen elmagyaráz mindent innentől kezdve azt sem tudom mondani, hogy a többi csapatnak nehéz lenne felvenni a fonalat. A videó egyébként nagyon szépen össze van rakva! Minden elismerésem.

Természeten nincs kifogásom a game-engine működés ellen. Abszolút túlteljesítettétek az első házit.

Egy kérdés merült fel: működik ez MVVM modelles GUI-val? Nem látom akadályát, de mégis. Feltételezem, hogy WPF-et akar majd a megjelenítés használni.

**Comment by kuklinistvan** [comment]
@pintergreg 

> Megértettem a különbséget, már a videó előtti két posztból is leesett, de azt is megnéztem.

Elnézést kérek a passzív rant-ért, gyakran mondták már (sokszor jogosan, néha nem), hogy túlbonyolítok dolgokat, és előfordul újabban, hogy túl gyorsan ugrok rá :)

> Egy kérdés merült fel: működik ez MVVM modelles GUI-val? Nem látom akadályát, de mégis. Feltételezem, hogy WPF-et akar majd a megjelenítés használni.

Egy lehetséges mód, ahogy elviekben működnie kell: a handle alapján mindig azonosítható a kikért játék objektum. Ha a GUI ez alapján mindig a megfelelő MVVM-es modellt frissíti, úgy minden további nélkül, igen.

> A videó egyébként nagyon szépen össze van rakva! Minden elismerésem.

> Abszolút túlteljesítettétek az első házit.

Köszönjük a bátorítást! Külön én a sok energiát ebbe a ticket-be, a konzultálásokra  :)

**Comment by kuklinistvan** [comment]
@pintergreg 

> Megértettem a különbséget, már a videó előtti két posztból is leesett, de azt is megnéztem.

Elnézést kérek a passzív rant-ért, gyakran mondták már (sokszor jogosan, néha nem), hogy túlbonyolítok dolgokat, és előfordul újabban, hogy túl gyorsan ugrok rá :)

> Egy kérdés merült fel: működik ez MVVM modelles GUI-val? Nem látom akadályát, de mégis. Feltételezem, hogy WPF-et akar majd a megjelenítés használni.

Egy lehetséges mód, ahogy elviekben működnie kell: a handle alapján mindig azonosítható a kikért játék objektum. Ha a GUI ez alapján mindig a megfelelő MVVM-es modellt frissíti, úgy minden további nélkül, igen.

> A videó egyébként nagyon szépen össze van rakva! Minden elismerésem.

> Abszolút túlteljesítettétek az első házit.

Köszönjük a bátorítást! Külön én a sok energiát ebbe a ticket-be, a konzultálásokra  :)

**Comment by vajnaivik** [comment]
Egy frissebb verzió az általam készített felépítésről:
![multinac](https://user-images.githubusercontent.com/61936589/108338187-4507a100-71d6-11eb-9f00-409ab7401264.png)

**Comment by kuklinistvan** [comment]
![firka1](https://user-images.githubusercontent.com/19473224/109142462-303f8600-775f-11eb-8a2c-af9530a6a82e.png)
![firka2](https://user-images.githubusercontent.com/19473224/109142467-3170b300-775f-11eb-880a-fbf3ff6ac022.png)

**Comment by goet** [comment]
#88
