### ISSUE TITLE
Kamera - Polygon színezés

### ISSUE THREAD

**Issue by Montamy** [SzFMV2021-Tavasz/AutomatedCar-A#45]
03.04-én megkérdezni, hogy itt mi az elvárás és azalpján átállítani a taskot.

**Comment by pintergreg** [comment]
@Montamy 
![Képernyőkép_2021-02-16_09-48-44](https://user-images.githubusercontent.com/3854784/109927217-25877280-7cc4-11eb-8d5b-6d38cf402e3d.png)

Így néz majd ki kb. a szoftver (ez a múlt félévesből screenshot), van az autó, előtte látsz egy kék háromszög( részlet)et. Az a kamera látómezeje (debug módban). A kamera pozícióját majd a következő sprintben fogja egy csapat folyamatosan kiszámolni.

Ebben a sprintben annyi kell tudnotok, hogy a képernyőn meg tudjatok jeleníteni 1 db színes háromszöget. Ha ez egy függvény, ami a canvasra rajzol, akkor majd a többi csapat a 2. sprintben meghívja 3 db ponttal és egy színnel.

Elnézést, de hirtelen nincs meg hogy ez a társaság akarja-e worldobject-ként reprezentálni a fenti háromszöget, ebben az esetben nem kell külön függvény, mert a normál world-object rajzolás is le tudja kezelni, csak arra kell figyelnetek, hogy nem egy képet kell hozzá megjeleníteni, hanem egy poligont.

**Comment by pintergreg** [comment]
A többi issue-ból értettem meg, hogy a kamera alatt a világ épp látható részét érted, nem a kamera modult a következő sprintből...

**Comment by goet** [comment]
Kicsit szerencsétlen elnevezés, mivel pontosan ugyanaz a neve mint a későbbi logikai dolgonak, de az itteni taskoknál a render kamerára gondoltunk, ami szűri hogy mi látható épp a képernyőn.
