### ISSUE TITLE
Stale függőségi referencia az AutomatedCar és BaseModelTest projektekben

### ISSUE THREAD

**Issue by Easimer** [SzFMV2021-Tavasz/AutomatedCar-A#55]
Az AutomatedCar és BaseModelTest projektekben bent maradt egy-egy referencia a BaseModel régi helyére:
https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/blob/9932a48e50fb7149dfa5fc0b406dfccffd6cf5b1/src/AutomatedCar/AutomatedCar.csproj#L16
https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/blob/9932a48e50fb7149dfa5fc0b406dfccffd6cf5b1/test/BaseModelTest/BaseModelTest.csproj#L30

Nem hiszem, hogy emiatt failel a CI build, de lehet köze van hozzá.

**Comment by pintergreg** [comment]
A @SzFMV2021-Tavasz/team-a2 áthelyezte a a BaseModelt egy másik mappába az #52 során. Ott önmagában még jó volt, de nyilván az összes olyan branch ami még azelőtt jött létre érintett lehet.

Ma már nem lesz erőm kód szinten belemenni, @kuklinistvan tud talán a leggyorsabban segíteni.
Holnap igyekszem megoldani, nem akarom, hogy egész hétvégén ne lehessen haladni.
