### ISSUE TITLE
Branch készítés permission hiányzik

### ISSUE THREAD

**Issue by goet** [SzFMV2021-Tavasz/AutomatedCar-A#66]
Befejeztem egy taskomat, lokális külön branchen dolgoztam, amikor megpróbáltam pusholni akkor a GitHub elutasított. A kliensen be van állítva az SSH, tegnap este használtam is egy saját repohoz, a csapatommal egyeztetve úgy tűnik csak valamiért hiányzik nekem a permission hozzá.
![image](https://user-images.githubusercontent.com/6637097/110167845-9f1f7d80-7df6-11eb-994f-1a350d62cda7.png)

**Comment by pintergreg** [comment]
Nem értem a dolgot. Az A4 csapat tagja vagy, azon keresztül pedig a Company-A-nak is. A Company-A minden tagja írási joggal rendelkezik az AutomatedCar-A repóhoz. Ez több más kollégának sem okozott gondot.

**Comment by pintergreg** [comment]
@goet Mi a helyzet, ha nem SSH-val, hanem HTTPS-sel csinálod? Az URL is https-es a képen.

**Comment by goet** [comment]
@pintergreg Sikerült, a Credential Managerben volt néhány régebbi gites dolog, tippre azok zavarhattak be, miután töröltem őket már engedte.
