### ISSUE TITLE
ImageRepository

### ISSUE THREAD

**Issue by goet** [SzFMV2021-Tavasz/AutomatedCar-A#67]
Különálló osztály ami betölti a képeket, és fájlnév alapján ezek lerkérhetőek belőle.
### Definition of Done

- [ ] Az összes képet betölti egy adatstruktúrába, ahonnan címezhetőek
- [ ] Event vagy flag segítségével jelzi ha ezzel kész van, és a Renderer már hozzányúlhat
- [ ] A képek címezhetőek a fájlnevükkel (RenderableWorldObject.Filename alapján lehessen elérni őket)

**Comment by pintergreg** [comment]
@goet  Ez tulajdonképpen kész van a skeletonban. Mármint az a logika, hogy ott én csak tisztán MVVM szerint rajzolok. Viszont anno egy tutorialkódból szedtem egy képfájl cache-elést:

https://github.com/SzFMV2021-Tavasz/AutomatedCar-A/blob/3592e40e65efac51f41ae12a4ce207767a878fbb/src/AutomatedCar/Visualization/WorldObjectTransformer.cs#L12-L31

Úgy működik, hogy a a képfájl neve van bindelve XAML-ben, amit a WorldObjectTransformer alakít képpé, de úgy, hogy közben egy Dict-ben cacheli a már betöltött képeket.

**Comment by goet** [comment]
Este már teljesen elkerülte a figyelmem, akkor ez az issue tárgytalan. Átírtam hogy a WorldRenderer is azt a dictionaryt használja.
