### ISSUE TITLE
Change gear with key press

### ISSUE THREAD

**Issue by remenyidamjan** [SzFMV2021-Tavasz/AutomatedCar-A#79]
- [ ] Az automata váltó 4 állapota szabályozható

- [ ] szekvenciális váltóról lévén szó, sorban állíthatók a fokozatok: P(ark), R(everse), N(eutral), D(rive)

- [ ] alaphelyzet: P, „felváltás” után R, majd N, majd D. „Leváltás” ugyanez visszafele.

**Comment by pintergreg** [comment]
Csak, hogy biztosra menjek, a button „click” itt ugye nem egérre vonatkozik? Csak billentyűzetről kell vezérelni a HMI kezelőszerveit, egérrel a dashboardon keresztül nem.

**Comment by remenyidamjan** [comment]
Igen, billentyuzetre gondoltam.

**Comment by engeldorian** [comment]
Ez igazából egy 2-3 perces task. Amit tudtam csinálni, hogy átírtam a pontokat a #78-ba. Igazából az a task sem sokkal több, de talán jobb ha 1 közösben van a kettő. Nem tudom mi a helyes procedúra ebben az esetben, én csak Close-olni tudom az Issue-t.

**Comment by pintergreg** [comment]
Simán le lehet zárni, mondván, hogy a #78 megoldja. Lehet neki invalid státuszt is adni, ha úgy gondolod, hogy ebben formában nem korrekt (mert annak a része). Más státusz címke még kevésbé jó erre a helyzetre. Esetleg a duplicate. Vagy tényleg csak lezárod.
